### ISSUE TITLE
add dialog options for the restoration project quest

### ISSUE THREAD

**Issue by Alpyspa** [BGforgeNet/Fallout2_Restoration_Project#330]
my issue is with vault village especially, the quest lacks dialog options, i told connar that i am going to help him buy guns, which i didnt mean to, i was only there for the money, i killed all the rats, went to the sergeant in vc and the only option i have is that vault city wants to enslave those people, i proceed with the option, but i am only told to finish my mission, even though all the rats are killed

**Comment by burner1024** [comment]
Do you want to write these?

**Comment by Alpyspa** [comment]
I would'nt mind helping you with that, the problem is that i have already finished the quest. Ill start a new game, get to that point and then i will try and make some new options. I will let you know in a couple of days when i have already made some lines

**Comment by burner1024** [comment]
Don't jump in yet, that wasn't a request, just a question.
I'd need to review the quest myself first.

And anyway, I'd suggest to keep multiple saves. Even with all the fixes, F2 engine still happens to crash from time to time.

**Comment by Alpyspa** [comment]
i wanted to ask you something, on my previous playthrough, i have noticed that in the ncr, at the slavers place outside of the city gates, if you use an electric lockpick on one of the doors insdie the building, the game would crash. do you think that has been fixed?

**Comment by burner1024** [comment]
I don't remember. It might have been, depending on what's your previous playthrough version was. Check out the changelog.

**Comment by Alpyspa** [comment]
that was 2.3 of the original rp i think

**Comment by burner1024** [comment]
A lot has changed since then. It's likely has been fixed, you can re-test.

**Comment by burner1024** [comment]
Well, there are dialog options to go for the money. Maybe you missed them.
